project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Intro R Tutorial.qmd"
    - "!Testing shinylive.qmd"
    - "!TestUploadData.qmd"


website:
  title: "Lewis & Clark College Data Science Resources Hub"
  navbar:
    left:
      - ditw.qmd
      - Cheatsheet.qmd
  favicon: science.png

format:
  html:
    theme: lux;
    navbar: purple;
    toc: true
    
    
