project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Intro R Tutorial.qmd"
    - "!Testing shinylive.qmd"
  resources: 
    - owid_co2_data_1.csv


website:
  title: "Olivia test - hello quarto"
  navbar:
    left:
      - about.qmd
      - hello.qmd
      - codechunks.qmd
      - Factor Tutorial.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
    
