project:
  type: website
  output-dir: docs

website:
  title: "Olivia test - hello quarto"
  navbar:
    left:
      - about.qmd
      - hello.qmd
      - codechunks.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true