project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Intro R Tutorial.qmd"
    - "!Testing shinylive.qmd"
  resources: 
    - owid_co2_data_1.csv
      #This loads our csv onto the site so it can be called up by users later


website:
  title: "Olivia test - hello quarto"
  navbar:
    left:
      - about.qmd
      - hello.qmd
      - codechunks.qmd
      - Factor Tutorial.qmd
      - brainstorm_612_lessons/climate_change_tutorial.qmd
      - Cheatsheet.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
    
