project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Intro R Tutorial.qmd"
    - "!Testing shinylive.qmd"
    - "!TestUploadData.qmd"
  resources: 
    - owid_co2_data_1.csv
    - data.csv
      #This loads our csv onto the site so it can be called up by users later
<<<<<<< HEAD
    - brainstorm_612_lessons/Images/salmon_dog.jpg
=======
    - 1900_census_race_and_birthplace.csv
>>>>>>> ae142eb586555d102a124bc1c91399ee2650057f


website:
  title: "Olivia test - hello quarto"
  navbar:
    left:
      - about.qmd
      - brainstorm_612_lessons/climate_change_tutorial.qmd
      - brainstorm_612_lessons/salmon_crossing_tutorial.qmd
      - Cheatsheet.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
    
