---
title: "Lewis & Clark College Data Science Resources Hub"
format: html
editor: visual
filters: 
  - webr
---

We have developed a variety of resources that teachers are welcome to use in their classrooms to teach R and data science. Below find links to our various resources.

[Link to github](https://github.com/Lewis-and-Clark-Data-Science): includes repositories with various tutorials

[Bio 110 R Data Science Tutorials:](https://lewis-and-clark-data-science.github.io/BIO-110-Web-Tutorials/) Online tutorials created for an intro to biology course which cover intro to R coding, data manipulation, basic visualization using ggplot, and inferential stats. Can be completed directly on a web browser (note: safari does not work).

[Data in the Wild Intro to Data Science Modules:](ditw.qmd) Modules developed for Lewis & Clark College’s Data in the Wild data science course. They cover basic data wrangling, graphing with ggplot and inferential statistics. They are files that must be opened in Rstudio desktop or posit.cloud (an online version of Rstudio). Follow the link for more information and to download the files.

[Data in the Wild Cheatsheet](Cheatsheet.qmd): List of commands used in the Data in the Wild Modules. 

[Data Science 140 Web Tutorials](https://lewis-and-clark-data-science.github.io/DSCI-140-Web-Tutorials/): Online web tutorials used in Data Science 140 at Lewis & Clark college. These are practice problems for students who are learning data science - they do not teach R from scratch (refer to the Bio110 and Data in the Wild modules for resources that teach R from scratch).

[Middle and High school Data Science Resources](https://lewis-and-clark-data-science.github.io/6-12-Data-Science-Resources/): This website has lesson plans, online coding tutorials, and other data science teaching resources for middle and high school teachers. It was developed through a teaching collaboration between 6-12 educators in the Portland area, Lewis & Clark undergraduates and professors, and University of Arizona faculty.

