---
title: "Test Upload Data"
format: html
editor: visual
---

## IPUMS Data

```{r}

# NOTE: To load data, you must download both the extract's data and the DDI
# and also set the working directory to the folder with these files (or change the path below).

if (!require("ipumsr")) stop("Reading IPUMS data into R requires the ipumsr package. It can be installed using the following command: install.packages('ipumsr')")

ddi <- read_ipums_ddi("usa_00002.xml")
data <- read_ipums_micro(ddi)
```

```{r}
plot(x=data$HHINCOME, y=data$HIGRADE)
```





## Census and Water quality data

Notes: Water data was from https://www.waterqualitydata.us/#countrycode=US&statecode=US%3A26&siteType=Facility&siteType=Aggregate%20groundwater%20use&siteType=Lake%2C%20Reservoir%2C%20Impoundment&siteType=Well&sampleMedia=Water&mimeType=csv&providers=NWIS&providers=STORET

Census data was from https://data.census.gov/table/ACSST1Y2021.S1902?q=income&g=040XX00US26$0500000&y=2021 

  - Search: Income and then on the sidebar choose county (I chose all Michigan counties data) and then can search a year (I chose 2021)
  


