--- 
title: "Bonneville Dam Data Exploration"
format: revealjs
---
```{r}
#| include: false
library(tidyverse)
library(DT)
url<- "https://lewis-and-clark-data-science.github.io/Olivia-test/brainstorm_612_lessons/data/Bonneville_Dam_1939_2023_Chinook_CSV.csv"
download.file(url, "Bonneville_Dam_1939_2023_Chinook_CSV.csv")
#Pulls data that has been loaded into the Olivia-Test github repo. 
Bon_chinook <- read.csv("Bonneville_Dam_1939_2023_Chinook_CSV.csv")
names(Bon_chinook) <- Bon_chinook[1,]
Bon_chinook <- Bon_chinook[-1,]
  #Move first row to header and delete the row
Bon_chinook_t <- t(Bon_chinook)
  #Transpose
colnames(Bon_chinook_t) <- Bon_chinook_t[1,]
Bon_chinook_t <- Bon_chinook_t[-1,]
  #Move first row to header and delete the row

Bon_chinook_t <- as.data.frame(Bon_chinook_t)

Bon_chinook_t <- Bon_chinook_t %>% replace(is.na(.), 0)
  #make NA into 0 values
Bon_chinook_t <- Bon_chinook_t %>% select(1:365)
  #Delete extra info we don't want 
#str(Bon_chinook_t)
  #Check what kind of data we have... Oh no! It's character data not numeric data
Bon_chinook_num <-Bon_chinook_t %>% mutate_all(function(x) as.numeric(as.character(x)))
  #Change character to numeric data
Bon_chinook_sum <-  Bon_chinook_num %>% mutate(sum_of_rows = rowSums(Bon_chinook_num))
  #Add a new column summing the rows

Bon_chinook_sum$year <- 2023:1938
  #Add a year column with just the year

options(scipen = 999) 
  #Don't use standard notation
Bonneville_chinook <- Bon_chinook_sum %>% mutate(sum_of_rows_100 = (sum_of_rows/1000))
```

## Let's look at the data more closely

Click through these slides to better understand what we're looking at. 

--- 

On the top of the data table, you'll see bolded numbers like **1/1**, **1/2**, etc. Do you have a guess what those might mean? Discuss with your neighbor and then click to the next slide to see the answer. 

---




## Here's our data again 

```{r}
#| echo: false
#| output: true
datatable(Bonneville_chinook, width=10, height=10, fillContainer=FALSE)
```

## Try again
```{r}
#| echo: false
#| output: true
knitr::kable(Bonneville_chinook, width=10, height=10, full_width=F, font_size=20, format="html")
```

